### ISSUE TITLE
Remove slash (/) character from header

### ISSUE THREAD

**Issue by prakdutt** [opendevl/Json2Flat#5] opened 2017-03-16 07:41 UTC
Hi

Thanks a lot for a great tool. This jar helps me a  lot to solve some on of my problems. I have one simple issue. I have a sample dataset like below which we are using to generate the csv file. The issue is that, the CSV file header becomes like
/name, /category, /author,/title,/price

I want to remove this / character from the csv file header. Please suggest, how it is possible.

[    {
		        "name":"dasd",
		        "category": "reference",
		        "author": "Nigel Rees",
		        "title": "Sayings of the Century",
		        "price": 8.95
		        
    },
   {
		        "category": "fiction",
		        "author": "Evelyn Waugh",
		        "title": "Sword of Honour",
		        "price": 12.99
		        
		    }
]

Thanks a lot.
Regards,
Prakash

**Comment by opendevl** [comment] 2017-03-16 18:00
Hello @prakdutt,
I have added the functionality that you have requested.
Please have a look at the README and JavaDoc.

**Comment by prakdutt** [comment] 2017-03-17 02:24
Hi,
Thanks a lot for your reply. 

It is working now.

Regards,
Prakash

**Comment by opendevl** [comment] 2017-03-17 02:56
@prakdutt If the issue is resolved can you please close the issue?

**Closed** 2017-03-17 02:57 UTC
