### ISSUE TITLE
Running this code on HDFS

### ISSUE THREAD

**Issue by NishantVerma07** [opendevl/Json2Flat#16] opened 2017-03-21 06:09 UTC
I am trying to convert a json file which is present on HDFS to CSV. Below two main classes I have tried for this:

1- 
public class ClassMain {

	public static void main(String[] args) throws IOException {
                String uri = args[1];
		String uri1 = args[2];
		
		Configuration conf = new Configuration();
		conf.set("fs.defaultFS", "hdfs:///ip-10-16-37-124:9000/");
		
		String str = new String(Files.readAllBytes(Paths.get(uri)));
		
		//FileSystem fs = FileSystem.get(URI.create("hdfs:///"+uri), conf);
		
		FileSystem fs = FileSystem.get(conf);
		FSDataInputStream in = null;
		FSDataOutputStream out = fs.create(new Path(uri1));
		try{
			
			in = fs.open(new Path(uri));
			JsonToCSV toCSV = new JsonToCSV(str);
			toCSV.json2Sheet().write2csv(uri1);
			IOUtils.copyBytes(in, out, 4096, false);
			
		}
		finally{
			IOUtils.closeStream(in);
			IOUtils.closeStream(out);
		}
	}
	}

I am running the jar as:
hadoop jar json-csv-hdfs.jar com.nishant.ClassMain /nishant/small.json /nishant/small.csv

But somehow, it reads as URI of my input file as hdfs:/ip-10-16-37-124:9000/nishant/small.json which is incorrect. I have tried all possible combinations of the URI, but it does not change the formed URI. I thought maybe Files.readAllBytes is causing problem while reading the JSON file, so I tried using buffer reader to read input file. Below is second main class I wrote for this.

2- 
public class ClassMain {

	public static void main(String[] args) throws IOException {
		Configuration conf = new Configuration();
		FileSystem fs = FileSystem.get(conf);
		Path inFile = new Path(args[1]);
		Path outFile = new Path(args[2]);

		if (!fs.exists(inFile))
		  System.out.println("Input file not found");
		
		if (!fs.isFile(inFile))
		  System.out.println("Input should be a file");
		if (fs.exists(outFile))
		  System.out.println("Output already exists");

		FSDataInputStream in = fs.open(inFile);
		FSDataOutputStream out = fs.create(outFile);
		byte buffer[] = new byte[12000];
		try{
			int bytesRead = 0;
		while ((bytesRead = in.read(buffer)) > 0) {
			String str = new String(buffer);
			JsonToCSV toCSV = new JsonToCSV(str);
			toCSV.json2Sheet().write2csv(outFile.toString());
		  out.write(buffer, 0, bytesRead);
		}
		}catch (IOException e) {
			         System.out.println("Error while copying file");}
		finally{in.close();
		out.close();
	}
	}	
}

Here, it is reading the input files alright. I tried printing the value of this.jsonString from JsonFlat.java and it was able to read the valid JSON. But the method call - 
ele = new JsonParser().parse(this.jsonString); is not going proper and it gives below stack trace:

Exception in thread "main" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 4 column 2
        at com.google.gson.JsonParser.parse(JsonParser.java:65)
        at com.google.gson.JsonParser.parse(JsonParser.java:45)
        at com.nishant.JsonToCSV.json2Sheet(JsonToCSV.java:105)
        at com.nishant.ClassMain.main(ClassMain.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 4 column 2
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505)
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1386)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:531)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:414)
        at com.google.gson.JsonParser.parse(JsonParser.java:60)
        ... 9 more

To call the parse method, it is sending this.jsonString as parameter which is a valid JSON as I have printed, then why is this giving malformed JSON exception. 

Is it because of "public JsonElement parse(Reader json) throws JsonIOException, JsonSyntaxException {" Reader data type?

How to run this code in HDFS which would solve my problem?

value of this.jsonString which is a valid JSON:

[
{"uploadTimeStamp":"1488793033624","PDID":"123","data":[{"Data":{"unit":"rpm","value":"100"},"EventID":"E1","PDID":"123","Timestamp":1488793033624,"Timezone":330,"Version":"1.0","pii":{}},{"Data":{"heading":"N","loc1":"false","loc2":"00.001","loc3":"00.004","loc4":"false","speed":"10"},"EventID":"E2","PDID":"123","Timestamp":1488793033624,"Timezone":330,"Version":"1.1","pii":{}},{"Data":{"xvalue":"1.1","yvalue":"1.2","zvalue":"2.2"},"EventID":"E3","PDID":"123","Timestamp":1488793033624,"Timezone":330,"Version":"1.0","pii":{}},{"EventID":"E4","Data":{"value":"50","unit":"percentage"},"Version":"1.0","Timestamp":1488793033624,"PDID":"123","Timezone":330},{"Data":{"unit":"kmph","value":"70"},"EventID":"E5","PDID":"123","Timestamp":1488793033624,"Timezone":330,"Version":"1.0","pii":{}}]},
{"uploadTimeStamp":"1488793167598","PDID":"124","data":[{"Data":{"unit":"rpm","value":"100"},"EventID":"E1","PDID":"124","Timestamp":1488793167598,"Timezone":330,"Version":"1.0","pii":{}},{"Data":{"heading":"N","loc1":"false","loc2":"00.001","loc3":"00.004","loc4":"false","speed":"10"},"EventID":"E2","PDID":"124","Timestamp":1488793167598,"Timezone":330,"Version":"1.1","pii":{}},{"Data":{"xvalue":"1.1","yvalue":"1.2","zvalue":"2.2"},"EventID":"E3","PDID":"124","Timestamp":1488793167598,"Timezone":330,"Version":"1.0","pii":{}},{"EventID":"E4","Data":{"value":"50","unit":"percentage"},"Version":"1.0","Timestamp":1488793167598,"PDID":"124","Timezone":330},{"Data":{"unit":"kmph","value":"70"},"EventID":"E5","PDID":"124","Timestamp":1488793167598,"Timezone":330,"Version":"1.0","pii":{}}]}]

**Comment by opendevl** [comment] 2017-03-21 07:45
@NishantVerma07 - We haven't thought of such a scenario. We will try to resolve the issue asap including hadoop support for the library.

**Comment by NishantVerma07** [comment] 2017-03-23 10:31
I wrote below main class for HDFS read and write.

public class ClassMain {

	public static void main(String[] args) throws IOException {
		
		Configuration conf = new Configuration();
		FileSystem fs = FileSystem.get(conf);
		Path inFile = new Path(args[1]);
		Path outFile = new Path(args[2]);
		FSDataInputStream in = fs.open(inFile);
		FSDataOutputStream out = fs.create(outFile);
		byte buffer[] = new byte[999999];
		try{
			int c = 0;
			while ((c = in.read(buffer)) != -1)  {
			String str = new String(buffer);
			JsonToCSV toCSV = new JsonToCSV(str);
			toCSV.json2Sheet().write2csv(outFile.toString());
			IOUtils.copy(in, out);
			out.write(c);
		}
			}
		catch (IOException e) 
		{
			System.out.println("ERROR*****************"+e);
		}
		finally
		{
		in.close();
		out.close();
		
		}
}	
}

And modified write2csv method as below:

public void write2csv(String destination, char delimiter)
			throws IOException {
		
		//for HDFS run
		org.apache.hadoop.conf.Configuration conf = new org.apache.hadoop.conf.Configuration();
		FileSystem fs = FileSystem.get(conf);
		System.out.println("DESTINATION::::::::::::::"+destination);
		Path out1 = new Path(destination);
		FSDataOutputStream out2 = fs.create(out1);
		if(fs.isFile(out1)){
			System.out.println("OK");
		}
		PrintWriter writer = new PrintWriter(new File(out2.toString()), "UTF-8");
		
		boolean comma = false;
		
		
		for (Object[] o : this.sheetMatrix) {
			String[] strArray = new String[o.length];
			for (int i = 0; i < o.length; i++) {
				//String [] strArr = null;
				strArray[i] = String.valueOf(o[i]);
				
			}
			comma = false;
			for (Object t : o) {
			
				if (t == null) {
					writer.print(comma == true ? delimiter : "");
					
					
				} else {
					writer.print(comma == true ? delimiter + t.toString() : t.toString());
					
				}
				if (comma == false)
					comma = true;
			}
			writer.println();
			
		}
		writer.close();
	}

But it has two problems:

1- It does not write the output CSV on HDFS. It instead creates a file with name of Output Data Stream and write the CSV in it. But this file is created on the path from where I submit the jar and nothing is written on HDFS.

2- It only reads JSON files of very small size. It does not read input JSON of size as small as 1 MB even.

**Comment by opendevl** [comment] 2017-03-23 12:55
@NishantVerma07 
The write2csv was designed only for local file system. It will not support HDFS file system for that you need to code it yourself.

I tried with a different approach.
Its working fine for the JSON that you mentioned.
I also tried it with a 1000 row JSON with a file size of 2.7MB, it's also working fine.
(Was unable to try with bigger file size coz the hadoop instance is running on a vm. Got stuck due to memory)

Give it a try and let me know if this works for you.

`import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.util.List;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.fs.FileSystem;
import org.apache.hadoop.fs.Path;

import com.github.opendevl.JFlat;

public class Check {

	public static void main(String[] args) throws IOException{
		
		Configuration conf = new Configuration();
		FileSystem fs = FileSystem.get(conf);
		Path inFile = new Path(args[0]);
		Path outFile = new Path(args[1]);
		
		BufferedReader br=new BufferedReader(new InputStreamReader(fs.open(inFile)));
        String line;
        line=br.readLine();
        
        String concatAllLines = line;
        while (line != null){
                //System.out.println("reading lines");
                line=br.readLine();
                System.out.println(line);
                if(line != null)
                	concatAllLines += line;
        }
        
        System.out.println(concatAllLines);
        
        System.out.println("Now JSON to CSV");
        
        List<Object[]> matrix = new JFlat(concatAllLines).json2Sheet().getJsonAsSheet();
        
        
        
        BufferedWriter bw =new BufferedWriter(new OutputStreamWriter(fs.create(outFile,true)));        
		boolean comma = false;
		for (Object[] o : matrix) {
			comma = false;
			String writeLine = "";
			for (Object t : o) {
				if (t == null) {
					writeLine += (comma == true ? "," : "");
				} else {
					writeLine += (comma == true ? "," + t.toString() : t.toString());
				}
				if (comma == false)
					comma = true;
			}
			writeLine += "\n";
			System.out.println(writeLine);
			bw.write(writeLine);
		}
		bw.close();
	}

}`

**Comment by NishantVerma07** [comment] 2017-03-24 06:55
worked OK for small file. Also worked OK for a JSON file of 1 MB . But taking a lot of time for a file of 130 MB size. Took more than 1 hour just to read the file, did not even start the conversion part.

**Comment by opendevl** [comment] 2017-03-25 16:03
@NishantVerma07 - This library isn't optimized to run in hadoop. It will take time to convert 130MB file.

**Comment by opendevl** [comment] 2017-03-28 03:53
@NishantVerma07 - can you please close the issue if it resolves the issue

**Closed** 2017-03-28 06:15 UTC
